# This is a basic workflow to help you get started with Actions

name: nerd-font

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install required packages
        run: |
            sudo apt-get update
            sudo apt-get install -y fontforge python3-argh python3-fontforge python3-argparse-addons python3-pkg-resources libargparse-dev

      # Runs a single command using the runners shell
      - name: Clone nerd fonts repo
        run: git clone https://github.com/ryanoasis/nerd-fonts.git -b v3.4.0 --depth=1

      - name: Download iosevka term curly font
        run: |
            chmod +x ./download_latest_iosevka.sh
            ./download_latest_iosevka.sh

      - name: Copy to nerd fonts dir
        run: |
            cp -r ./iosevka-term-curly/IosevkaTermCurly ./nerd-fonts/src/unpatched/
    
      - name: Build the nerd font
        run: |
            cd ./nerd-fonts
            ./bin/scripts/gotta-patch-em-all-font-patcher\!.sh /IosevkaTermCurly
            tar -cvzf ./iosevka-term-curly-nerd-font.tar.gz ./patched/IosevkaTermCurly/*       


      # Runs a set of commands using the runners shell
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: iosevka-term-curly-nerd-font.tar.gz
